service: volleyball-fixture-notifier

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ${opt:region, self:custom.defaults.region}

custom:
  defaults:
    region: ap-southeast-2

plugins:
  - serverless-python-requirements

functions:
  cronHandler:
    handler: src/infra/aws/lambda_handler.run
    events:
      # Invoke Lambda function every Sunday at 7pm
      # https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-cron-expressions.html
      - schedule: cron(0 19 ? * SUN *)
